######### QUERY #2.1 METADATA #####################

### USE CASE #1: Transparency and monitoring
### USE CASE #4: Analyzing eProcurement procedures

### Competency Question: List of procurement procedures awarded.

#################################################

select distinct ?procurement_procedure ?procurement_procedure_title ?contract where { 
	?procurement_procedure a :ProcurementProcedure;
                        :includesLot ?Lots.
    ?contract a :Contract;
              :refersToLot ?Lots.
    optional{ ?procurement_procedure :hasProcurementProjectTitle ?procurement_procedure_title.}
}

#################################################