######### QUERY #2.3 METADATA #####################

### USE CASE #1: Transparency and monitoring
### USE CASE #4: Analyzing eProcurement procedures

### Competency Question: List of procurement procedures that includes more than one lot and are awarded.

#################################################

PREFIX : <http://data.europa.eu/ePO/ontology#>

select distinct ?procurement_procedure ?procurement_procedure_title (count(?Lots) as ?number_of_lots)  where { 
	?procurement_procedure a :ProcurementProcedure;
                        :includesLot ?Lots.
    ?contract a :Contract;
              :refersToLot ?Lots.
    optional{ ?procurement_procedure :hasProcurementProjectTitle ?procurement_procedure_title.}
} group by ?procurement_procedure ?procurement_procedure_title having (?number_of_lots>1)
