######### QUERY #1 METADATA #####################

### USE CASE #1: Transparency and monitoring
### USE CASE #4: Analyzing eProcurement procedures

### User Story: As Procuring Entity, I want to know what Procurement Procedures have not been awarded so I can improve future Procurement Procedures.

### Competency Question: Yearly (2017) number of procurement procedures not awarded.

#################################################

PREFIX : <http://data.europa.eu/ePO/ontology#>

select (count(distinct ?procurement_procedure) as ?number_procurement_procedures) where { 
	?procurement_procedure a :ProcurementProcedure;
                        :includesLot ?Lots.
    optional{ 
        ?procurement_procedure :hasProcurementProjectTitle ?procurement_procedure_title.
    }
    filter not exists{
        ?contract a :Contract;
                  :refersToLot ?Lots.}
}

#################################################
