######### QUERY #1.1 METADATA #####################

### USE CASE #1: Transparency and monitoring
### USE CASE #4: Analyzing eProcurement procedures

### User Story: As Procuring Entity, I want to know what Procurement Procedures have not been awarded so I can improve future Procurement Procedures.

### Competency Question: Number of procurement procedures notified on TED.

#################################################

PREFIX : <http://data.europa.eu/ePO/ontology#>
select (count(?procurement_procedures) as ?all_proc_proc) where {
    ?procurement_procedures a :ProcurementProcedure.
}

#################################################
