######### QUERY #5.1 METADATA #####################

### USE CASE #4: Analyzing eProcurement procedures

### User Story: As a Contracting Authority, I want to know the percentage of contracts awarded segmented by contract nature, so I can prepare the annual report.

### Competency Question: List of nature types and the number of procurement procedures.

#################################################

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://data.europa.eu/ePO/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?ContractNatureType (count(distinct ?awarded_pp) as ?number_awarded_procurement_procedures) 
where {
    ?awarded_pp a :ProcurementProcedure ;
                :includesLot ?lots.
    ?contract a :Contract;
              :refersToLot ?lots;
     	 :hasContractPurpose ?Purpose .
   	?Purpose :hasContractNatureCodeType ?ContractNatureType.
}  group by ?ContractNatureType

#################################################