########## Competency Question CQ#7 ##########

### Use Case #1: Transparency and Monitoring
### Use Case #4: Analyzing eProcurement procedures

### Competency Question description: For a given period of time, the number of SMEs awarded.
### Note: modify the dates to get different results.

################################################

PREFIX : <http://data.europa.eu/ePO/ontology#>
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?Winner_Name ?WinnerSize ?Awarded_Date where { 
	?Award_Result :hasWinner ?Winner ;
              :hasAwardResultDateOfConclusion ?Awarded_Date .
    ?Winner :usesEOIndustryClassificationType ?WinnerSize ;
            rov:legalName  ?Winner_Name .
}