######### QUERY #2 METADATA #####################

### USE CASE #1: Transparency and monitoring
### USE CASE #4: Analyzing eProcurement procedures

### User Story: As a Procuring Entity, I want to know the percentage of Procurement Procedures divided into lots last year, so I can prepare the anual report.

### Competency Question: For a given period, percentage of procurement procedures divided into lots.

#################################################

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://data.europa.eu/ePO/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select (count(DISTINCT ?o) / (count (?o)) * 100 as ?Percentage)
where { 
	?o a :ProcurementProcedure ;
    	:includeLot ?Lot .
} 

#################################################