########## Competency Question # 09 ##########

### Competency Question #Q9: For a given CPV, the number of contracts awarded for that CPV and the total amount awarded;

################################################


PREFIX : <http://data.europa.eu/ePO/ontology#>

SELECT ?cpv (COUNT(DISTINCT(?contract)) AS ?number_contracts) where { 
	?contract a :Contract;
        :hasContractPurpose ?purpose.
    ?purpose :hasCPVType ?cpv.
} group by ?cpv order by desc(?number_contracts)