######### QUERY #1 METADATA #####################

### USE CASE #1: Transparency and monitoring
### USE CASE #4: Analyzing eProcurement procedures

### User Story: As Procuring Entity, I want to know what Procurement Procedures have not been awarded so I can improve future Procurement Procedures.

### Competency Question: Yearly (2017) number of procurement procedures not awarded.

#################################################

PREFIX : <http://data.europa.eu/ePO/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select DISTINCT(count(?o) as ?Number_Proc_Procedures) ?Year
where { 
    ?o a :ProcurementProcedure ;
     :hasAwardDateScheduled ?date .
   		 FILTER
    (year(?date) > year(now())-10).
}
GROUP BY ?o (year(?date) as ?Year)

#################################################
