######### QUERY #2.2 METADATA #####################

### USE CASE #1: Transparency and monitoring
### USE CASE #4: Analyzing eProcurement procedures

### Competency Question: List of procurement procedures that includes more than one lot.

#################################################

PREFIX : <http://data.europa.eu/ePO/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select ?procurement_procedure (count(?divided_lot) as ?number_of_lots) where { 
            ?procurement_procedure a :ProcurementProcedure;
                           :includesLot ?divided_lot.
            ?divided_lot a :Lot.
	} group by ?procurement_procedure having (?number_of_lots>1)
