########## Competency Question CQ#8.1 ##########

### Use Case #1: Transparency and Monitoring
### Use Case #4: Analyzing eProcurement procedures

### Competency Question description: List all the Procuring Entities, their IDs and their countries.

################################################

PREFIX : <http://data.europa.eu/ePO/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

select ?procuring_entity ?identifier ?country where { 
	?procuring_entity :hasProcuringEntityType ?peType ;
    	org:identifier ?identifier ;
     	org:hasSite ?site .
    ?site vcard:hasAddress ?address .
    ?address vcard:country-name ?country . 
}